"""Loans models — Loan, ListenEvent, OverrideLog.

Minimal placeholder; full schema lands in plan/0001 task #11
("Create loans app: checkout / return / expiry with property tests").

Planned shape:
    Loan         (id, kid_id, item_id, checked_out_at, expires_at,
                  returned_at?, progress_seconds)
    ListenEvent  (id, loan_id, occurred_at, position_seconds, kind)
    OverrideLog  (id, parent_id, kid_id, item_id, granted_at, reason)
"""

from django.db import models


class Loan(models.Model):
    """A checked-out item assigned to a kid.

    Placeholder: kid FK only. Full fields land with plan/0001 task #11.
    """

    kid = models.ForeignKey("kids.Kid", on_delete=models.CASCADE, related_name="loans")
    kid_id: int  # auto-generated by Django's FK descriptor; declared for pyright

    class Meta:
        app_label = "loans"

    def __str__(self) -> str:
        return f"Loan(id={self.pk}, kid={self.kid_id})"
