# Generated by Django 5.2.14 on 2026-05-18 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='kids.kid')),
            ],
        ),
    ]
